### ISSUE TITLE
Singularity missile is unselectable

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#147]

**Comment by Sharkgamedev** [comment]
Have ColVols been checked? Those are probably off because it seems that despite my best efforts either I'm doing something wrong or Spring does not read the .SpringHeight vectors in .dae files but it seems to do so with .s3o files so perhaps colvols just need to be manually specified in metadata, smiliar to caretaker?

**Comment by Arch-Shaman** [comment]
I've found the issue.
