### ISSUE TITLE
General change recommendations for commanders and other things.

### ISSUE THREAD

**Issue by Majo-R** [Arch-Shaman/ZK-Futurewars-Mod#396]
Alright this is going to be a bit random for how the modules and stuff goes but I'll try to keep it in order.
The main goal of these changes are to make the end-point of a "build" as strong as it can be at a metal cost inefficenty to balance it out.
So for example if someone wants to build a Heat-Ray commander that can 1v1 Dante in melee range they can do it but it will cost a more than Dante would.

Nanolathe/Build Power
Increase cost to 150m per module.
Give 2.5 BP version to the Riot and Siege commanders.
Give 5 BP version to Strike and Recon commanders.
Leave 7.5 BP with Engineer.

Pretty good overall, it's a very versatile statistic to have, being a strong flex constructor is great for either reclaim or building.

Lazarus/Support Package
Buff it to 25 BP and make it cost between 250m or 300m. Maybe even 500m cost depending on how strong it really is.

Great unlock for the engineer, reviving units is amazing on it's own even without the BP increase.

Personal Shield
Cost: From 300m to 250m.
Shield Radius: From 80 to 120 or 150. Which ever is big enough to block most small AoE hits.
Shield HP: From 1250 to 2500.
Shield Regen: From 16 to 25.

Could use a big buff, it prevents cloak/stealth and costs 300m. One module of Ablative Armor Plate gives 1250 HP for 150 metal. 
Beyond the shield blocking minor amounts of status effect damage it's worth a bit less as it is now.

Area Shield
Cost: From 250 to 500/750/900. The 500 cost is for the current stats, 750 is if it's buffed to the following stats and 900 if the stacking shield is added.
Shield Radius: From 350 to 400.
Shield HP: From 3600 to 7500.	<- Bugged ingame? Says maximum is 3600 but it charges up to 6000.
Shield Regen: From 50 to 75.
Shield Regen Cost: From 12 to 30.

Shield stacking? Long ago there used to be a change or a bug that allowed commanders to keep their Personal Shield after upgrading to Area Shield, so they effectively had two shields, one that prevented artillery hits and other that prevented raider unit attacks. If it's possible to restore this functionality without it causing bugs it would be insanely good and the reason for the 900m cost.

Area shield is amazing in comparison to the Personal shield and makes it worth giving away ability to cloak. 
It's big enough to allow the commander to run a circle of screening units to prevent the commander's hard-counter units from sniping it out of nowhere. 
Also lets the commander form part in shield balls.
Great overall, just buff it slightly so it looks better compared to Aspis you can place for 400 and have it do the same thing.

Safeguard - The Massive Area Shield building.
Cost: From 6000 to 5000 or 4000.
Regen: From 500 to 1000.
Regen Cost: From 70 to 75.
Regen Delay: From 20s to 15s.
Radius: From 1100 to 1200.

Cost vs efficency of Safeguard is a bit broken, I don't see it used as a big rear-guard economy shield as much as I've seen it used as a bigger regular shield, haven't seen it used much outside of vs AI games.
For the cost of 6000 metal you could have made 2 fusion generators and 1 singularity generator. OR you could have made 1 silo and 1 full Nuke before the shield is charged enough to block even the 1750 tactical nuke.
It's potential is great it just requires too much investment for the current cost.

Radar Jammer
Cost: From 500 to 200.
Radar Jamming: From 350 to 500.

Radar Jammer needs a big buff.
As it is it gives 350 Radar Jamming for 500 metal while for 350 metal Owl/Agitator gives 600 Radar Jamming AND 2400 radar with 1700 vision and sonar.
The stat changes I gave should work, though keeping 500 metal price and then overbuffing the radarjamming to 600 or 750 range could also work.

Area Cloak/Cloaking Field
Cost: From 600 to 500.
Radius: From 350 to 400.

Area cloak is great, though 600 is a bit expensive when Cornea/Iris is 500 metal.

High Power Servos
Cost: From 100 to 250.
Increase Speed: From 2.2 to 3.

Speed is always great to have and gives commanders a big degree of survivability.
However it's easy to "cheat" speed to commanders by using Hercules or Lobsters, so you might have a really slow commander but it doesn't matter because the player got some form of transport to avoid the issue.
Making the speed module stronger should help commanders have an edge without an assistant wheelchair unit.

Strike Servos
Cost: From 100 to 450.
Increase Speed: From 4 to 5.
Health Decrease: From 275 to 0. Just remove it.

Strike servos are amazing for what it does, but also cheap and the health decrease is miniscule and just annoying to make the commander choose 2x Strike Servo + 1 Armor Plate for a level instead of 3x Strike Servo.
It's funny to combine strike servos with autorepair and Nuke modules to get a below 1000 HP kamikaze commander but other than that it's both annoying to the player trying to use the commander and OP to the enemy getting hercules dropped by a commander that has 200 HP and explodes like a nuke when a single Gauss shot kills it.
No seriously, get a Recon commander, give it 8x Strike Servo+AutoRepair+3x Nuke and you get 200HP death commander.
7475 Metal cost Nuke you can stealth deploy into enemy lines. 9175 Metal if you give the commander 4 long distance jump jet upgrades so it can jump into the enemy no issue.

Autorepair
Cost: From 150 to 175.
Repair Speed: Keep as is.
Health Decrease: From 75 to 0. Just remove it.

Same deal as strike servos when it comes to health decrease, it's just an annoying balance part of the module that can be swapped with metal cost change.
It's as strong as single Caretaker healing the commander but always active, so should be good value for HP/s.

Nanobot Sleave/Strike com's stealth regen
Cost: From 75 to 175.
Repair Speed: From 20 to 25.

Strong autorepair that works only when commander is cloaked, great for the hit-and-run that commander is meant to do, a bit cheap though, the increase in price shouldn't be too great with the repair speed increase.

Ablative Armour Plates
Cost: From 150 to 250
Health Addition: Keep as is.

It's a health padding module, as simple as it can be, get all 8 and you get 10000HP to avoid getting assassinated. Bump the price so players make a choice of having more HP and taking bigger risks or risking getting killed easily if they choose other modules.

Damage Module:
Cost: From 100 to 300
Damage Increase: From 10% to 12.5%
Speed Decrease: From 0.75 to 0. Just remove it.

Damage increase, simple as the armor module but better than armor, you get more health by killing the enemy faster than enemy can damage you, so slightly more expensive than armor module.
Changing value from 10% to 12.5% will get to 100% if all 8 modules are taken.

Range Module(Non-Bombard):
Cost: From 100 to 600
Range Increase: From 10 to 12.5%
Speed Decrease: From 0.75 to 0.

Range Module(Bombard):
Cost: From 100 to 900
Range Increase: From 10 to 12.5%
Speed Decrease: From 2 to 0.

As it is Range increase is one of the most powerful modules available to commander, if you put two commanders to fight and one has 8 range modules while other has 8 any other modules the range module will win nearly always. 
Range effectively acts as both speed and damage module in one which should balance out with the cost I'm proposing, it's strong, you just got to pay for that strength.
Buffing it to 12.5% puts it in line with damage module to give 100% increase when maxed out, and the cost difference between other commanders and the siege/bombard commander is to compensate for the already big range of the stock weapons Siege commander has access to.
Speed decrease removal is in line with damage, autorepair and speed modules, it's just annoying balance that can be simply swapped with increased metal cost.

Other changes would be maybe giving Riot Commander a type of Clarity/Outlaw weapon or ability with bigger range/AoE, that would allow it type of bulldozing attack where stealth doesn't work as well.

For weapons there's a weird line between Engineer's Sniper, Heavy Beam Laser and Heavy Particle Laser that I'll have to get around to, for now that's it for today, I'll keep as a doc on my PC and expanding as I go along.

**Comment by LeojEspino** [comment]
I agree with most of these changes but there are some that I want to say

I think buffing the speed of how much servos give might make some comms more annoying to deal with (notably Ghost commander and Bombard commander, with Ghost already being rather fast), also I'd like to keep strike servos hp reduction, otherwise its a straight upgrade from normal servos but just expensive, and buff its cost to 300 instead of 450

I think your overpricing range and damage module, for damage, sure the faster you kill the less damage you take, but your easier to kill rather than just being a tank, who can shrug off more and survive easier, I think around 200-250 pricing is good enough. 600/900 metal for one single range module is rather ludicrous, range is powerful but 12.5% is too low for that cost, I think 300-400 for range module is good enough, 500 for Bombard.

What I say might be wrong here however its simply my opinion, its probably a good idea to test these kinds of changes in a test version

**Comment by LeojEspino** [comment]
A

**Comment by Arch-Shaman** [comment]
First off, thank you for the feedback. I appreciate the time you've taken to put all this together. There are some points I'd like to discuss further, though in general I think a lot of this I'd agree with minus some of the numbers. I'd like to apologize in advance if leoj scared you a bit with the issue being closed. Anyways there's a few points (in nonspecific order) I'd like to discuss further, mostly the numbers. I disagree a bit with the idea of making commanders cost inefficient. I'd rather see them just a bit under dante power level for cost rather than being wholly metal inefficient. That said, I'm not against raising the cost of some things or taking some of your suggestions in. As is, comms are generally allowed to be a lot more metal efficient than ZK comms because their counters are much stronger than in ZK. For instance, 2x lance will kill most commanders pretty easily or the odd skuttle. I don't think comms can actually reach the level of soloing dante/vulcan. Generally they die to any of the heavies out there (Breaker / Grizzly is notorious for killing comms really easily) and their price point is around lv5 - 6 commorph, depending on module. I really would like to avoid commorph being unviable like the plague. My preferred balance here is it being an option, but not a must do.

```Strike Servos
Cost: From 100 to 450.
Increase Speed: From 4 to 5.
Health Decrease: From 275 to 0. Just remove it.

Strike servos are amazing for what it does, but also cheap and the health decrease is miniscule and just annoying to make the commander choose 2x Strike Servo + 1 Armor Plate for a level instead of 3x Strike Servo.
It's funny to combine strike servos with autorepair and Nuke modules to get a below 1000 HP kamikaze commander but other than that it's both annoying to the player trying to use the commander and OP to the enemy getting hercules dropped by a commander that has 200 HP and explodes like a nuke when a single Gauss shot kills it.
No seriously, get a Recon commander, give it 8x Strike Servo+AutoRepair+3x Nuke and you get 200HP death commander.
7475 Metal cost Nuke you can stealth deploy into enemy lines. 9175 Metal if you give the commander 4 long distance jump jet upgrades so it can jump into the enemy no issue.
```

If the health malus is too minuscule, why not increase the health malus and the effect to make it more interesting? I'm thinking:

Speed: +4 -> +6
HP: -275 -> -600 (-68.75 hp per speed -> -100/speed, nearly double the malus)
Cost: 100 -> 175

The malus was added to give players an option to take on a big speed buff in exchange for less hp (like a raider almost). This is why it is exclusive to Ghost / Recon comm. I didn't want to overdo it at the time such that it would be a Never Use module, which is why we have what we currently have.

```Safeguard - The Massive Area Shield building.
Cost: From 6000 to 5000 or 4000.
Regen: From 500 to 1000.
Regen Cost: From 70 to 75.
Regen Delay: From 20s to 15s.
Radius: From 1100 to 1200.

Cost vs efficency of Safeguard is a bit broken, I don't see it used as a big rear-guard economy shield as much as I've seen it used as a bigger regular shield, haven't seen it used much outside of vs AI games.
For the cost of 6000 metal you could have made 2 fusion generators and 1 singularity generator. OR you could have made 1 silo and 1 full Nuke before the shield is charged enough to block even the 1750 tactical nuke.
It's potential is great it just requires too much investment for the current cost.
```

The regen delay I'm considering a different kind of buff. 20s is a bit absurd, so why not use our SWOD system to improve the downtime? Alternatively, I'm thinking:

Regen Cost: 70 -> 80
Cost: 6k -> 5,5k
Regen Delay: 20s -> 8s
Radius: 1100 -> 1200
Regen would remain same


```Range Module(Non-Bombard):
Cost: From 100 to 600
Range Increase: From 7.5 to 12.5%
Speed Decrease: From 0.75 to 0.

Range Module(Bombard):
Cost: From 100 to 900
Range Increase: From 10 to 12.5%
Speed Decrease: From 2 to 0.
```

On here I'd like to compromise on the range module change for bombard. I'd say remove the speed malus and remove speed buff or make speed module worse for bombard. Bombard is a traditional artillery piece, as such I'd rather see it slow than be rather mobile. Note: Non-bombard range in your suggestion was wrong (Bombard gets +10%, non gets +7.5%). In general I'd like to avoid commanders being watered down generalists as much as possible and give them their own niches. That said, I have an idea: what if we introduced a module that negated the speed malus that could cost a fair chunk of change?

```
Ablative Armour Plates
Cost: From 150 to 250
Health Addition: Keep as is.
```

9e4c2768b6a9d1a2a3238b27677c50e06010153c -- approved.

```
Cost: From 100 to 300
Damage Increase: From 10% to 12.5%
Speed Decrease: From 0.75 to 0. Just remove it.

Damage increase, simple as the armor module but better than armor, you get more health by killing the enemy faster than enemy can damage you, so slightly more expensive than armor module.
Changing value from 10% to 12.5% will get to 100% if all 8 modules are taken.
```

Seems alright to me. I think 300 is a bit high in my opinion, I'd like to start at 200. Speed malus: see above.

```Nanobot Sleave/Strike com's stealth regen
Cost: From 75 to 175.
Repair Speed: From 20 to 25.

Strong autorepair that works only when commander is cloaked, great for the hit-and-run that commander is meant to do, a bit cheap though, the increase in price shouldn't be too great with the repair speed increase.```

I think 75 -> 150 here would be better. I worry about the competition with autorepair your suggestion would bring.

```Autorepair
Cost: From 150 to 175.
Repair Speed: Keep as is.
Health Decrease: From 75 to 0. Just remove it.
```
e73f0bf -- approved.

```Ablative Armour Plates
Cost: From 150 to 250
Health Addition: Keep as is.```

I'm a bit confused on the risk you'd be taking honestly. It's already risky with ultimatiums, skuttles, and lances floating around.

```
Radar Jammer
Cost: From 500 to 200.
Radar Jamming: From 350 to 500.

Radar Jammer needs a big buff.
As it is it gives 350 Radar Jamming for 500 metal while for 350 metal Owl/Agitator gives 600 Radar Jamming AND 2400 radar with 1700 vision and sonar.
The stat changes I gave should work, though keeping 500 metal price and then overbuffing the radarjamming to 600 or 750 range could also work.
```

I'm more or less fine with this though I'd rather have radar jamming go up to 425 or 400. Radar jamming is incredibly strong in FW. It stops artillery from getting counter artilleryed. At some point I thought of getting rid of it entirely.


```High Power Servos
Cost: From 100 to 250.
Increase Speed: From 2.2 to 3.

Speed is always great to have and gives commanders a big degree of survivability.
However it's easy to "cheat" speed to commanders by using Hercules or Lobsters, so you might have a really slow commander but it doesn't matter because the player got some form of transport to avoid the issue.
Making the speed module stronger should help commanders have an edge without an assistant wheelchair unit.
```

I'm considering splitting the speed upgrade into three tiers like the bp suggestion.

Slow (Riot / Bombard)
Cost: 200
Speed: 1.5

Medium (Support / Strike)
Cost: 175
Speed: 2.5

Fast (Recon)
Cost: 150
Speed: 3

Recon as is is pretty underused outside of the nuke comm build. I'd like to buff it a bit more.

I'll continue tomorrow morning, as I am a bit tired right now.

**Comment by Majo-R** [comment]
Yeah I can see your point for the metal costs being high, I tried to keep it from being too cheap so I've overshoot there.
As for the pricey speed malus negation module I'm all for that, and would forward it towards the increased HP malus on the speed module.
Having an end-point counter-weight to a build that has 8 range or speed modules sounds amazing. You don't really need it but it's there if you want to dump the metal in for it.

**Comment by Arch-Shaman** [comment]
https://github.com/Arch-Shaman/ZK-Futurewars-Mod/commit/3c000052e2065c5a92adb0d51d47822f79f838fd Radar jammer Buff:
Cost: 500 -> 300.

**Comment by Arch-Shaman** [comment]
a283513 : Servos split into three.

**Comment by Arch-Shaman** [comment]
Closing due to mostly implemented / out of date feedback. Feel free to re-open with new feedback. Thanks again.
