### ISSUE TITLE
"Heretic" (bomberstrike) has reload bar

### ISSUE THREAD

**Issue by DiligentDolphin** [Arch-Shaman/ZK-Futurewars-Mod#567]
**Description of bug**: "Heretic" (bomberstrike) has both reload / rearming attack cool down,
either of them are effective, make it can reload like ground unit
without a landing pad.  Remove reload property and fix.
**Version Encountered in**: v0.37.17 (commit 31e275f7c08b428b5b9908501bde8e1d38a06b81)
**Modoptions, if any**: nil.
**Replay, if any**: Remove line 85 "reloadtime" in "units/bomberstrike.lua" can fix.

**Infolog**: nil.

**Comment by Arch-Shaman** [comment]
First, thanks for the report. 

Second to clarify: 31e275f is not live. https://github.com/Arch-Shaman/ZK-Futurewars-Mod/commit/c5672f1390951a021f7504911ef3e5c77ddbff88 is the last live commit. This is mostly because we're waiting for zk stable.

This bug actually affects all bombers and is mostly a cosmetic thing under most situations. I've "fixed" this by making bombers not show up in the reload bar. This is a crude fix, but should be good for the time being.

**Comment by Arch-Shaman** [comment]
Confirmed fix by e75235a.
